---
title: "EDA_LA1_Reshma"
author: "Reshma Itagi"
date: "2022-09-23"
output:
  pdf_document: default
  html_document:
    df_print: paged
dataset: Test_scores.csv
---
```{r}

```

```{r}
search()
help.start()
help('vector')
?vector
apropos('vector')
#installed.packages()
2+2
3-2
8*8
18/2
pi
pi*2
3^3
sqrt(5)
abs(-8)
factorial(5)
log(2,base=10)
log10(2)
log2(6)
exp(2)
cos(30)
sin(45)
tan(45)
data1 = c(1,2,3,4,5)
data1
data2=c(data1,7,8,9)
data2
data3 = scan()
data3
day2 = scan(what = 'character')
day2
getwd()
dir()
list.files()
ls()
rm(day2)


```

```{r}
df = read.csv('test_scores.csv')
head(df)
```

```{r}
library(dplyr)
quantile(df$posttest)
fivenum(df$posttest)
data2=df
data2.mat=as.matrix(data2)
data2.mat=as.matrix(data2)
data2.mat
frame.list=as.list(data2)
frame.list
frame.list=as.list(data2)
frame.list
sd(data2$posttest)
length(na.omit(data2$posttest))
t(data2)
length(na.omit(data2$posttest))
margin.table(data2$posttest)
prop.table(data2$posttest)
stem(data2$posttest)
sample(data2,size=10,replace=TRUE)

table(data2$posttest)
plot(data2$pretest)
boxplot(data2$pretest)
data2.stack=stack(frame.list)
data2.stack
unstack(data2.stack)
fac=factor(data2$posttest)
fac
```

```{r}
str(df)
```

```{r}
head(df)
```

```{r}
sapply(df,class)
```

```{r}
colnames(df)
```

```{r}
rownames(df)
```

```{r}
summary(df)
```

```{r}
class(df)
```
```{r}
min(df$posttest)
```

```{r}
mode(df$posttest)
```

```{r}
median(df$posttest)
```

```{r}
mean(df$posttest)
```

```{r}
sum(df$posttest)
```

```{r}
sort(df$posttest)
```

```{r}
order(df$posttest)
```

```{r}
rank(df$posttest)
```

```{r}
dimnames(df)
```

```{r}
length(df$posttest)
```

```{r}
df$student_id
```

```{r}
df$posttest
```

```{r}
df$posttest[3]
```

```{r}
df$school[3]
```

```{r}
df$posttest[1:5]
```

```{r}
data.frame(df)
```

```{r}
View(df)
```

```{r}
names(df)
```
```{r}
row.names(df)
```

```{r}
col(df)
```

```{r}
colnames(df)
```

```{r}
length(df)
```

```{r}
str(df)
```
```{r}
ls(df)
```

```{r}
ls.str(df)
```

```{r}
ls.str(pattern = 'df')
```

```{r}
dim(df)
```

```{r}
dimnames(df)
```

```{r}
head(df)
```
```{r}
head(df,n=3)
```

```{r}
head(df$student_id)
```

```{r}
head(df$pretest)
```

```{r}
head(df$posttest)
```

```{r}
head(df$gender)
```

```{r}
head(str(df))
```

```{r}
head(structure(df))
```

```{r}
head(structure(df$n_student))
```

```{r}
head(structure(df$posttest))
```

```{r}
fivenum(df$pretest)
```

```{r}
tail(df)
```

```{r}
tail(df, n=3)
```

```{r}
tail(df$student_id)
```

```{r}
tail(df$posttest)
```

```{r}
tail(str(df))
```

```{r}
tail(structure(df))
```

```{r}
tail(structure(df$pretest))
```

```{r}
class(df)
```

```{r}
class(df$student_id)
```

```{r}
class(df$posttest)
```

```{r}
class(dim(df))
```

```{r}
class(dimnames(df))
```

```{r}
summary(df)
```

```{r}
summary(df$student_id)
```

```{r}
summary(df$posttest)
```

```{r}
summary(df$gender)
```

```{r}
mean(df$posttest)
```

```{r}
median(df$posttest)
```
```{r}
mode(df$posttest)
```

```{r}
mad(df$posttest)
```

```{r}
sd(df$posttest)
```

```{r}
var(df$posttest)
```

```{r}
quantile(df$posttest)
```

```{r}
quantile(df$n_student)
```

```{r}
var.test(df$pretest, df$posttest)
```

```{r}
var.test(df$posttest, df$pretest)
```

```{r}
tdf= attach(df)
tdf
```

```{r}
max(df$pretest)
```

```{r}
min(df$pretest)
```

```{r}
head(stack(df))
```

```{r}
head(sort(df$pretest))
```

```{r}
head(sort(df$posttest))
```

```{r}
tail(sort(df$pretest))
```

```{r}
tail(order(df$posttest))
```

```{r}
head(rank(df$posttest))
```

```{r}
tail(rank(df$posttest))
```

```{r}
df[3,3]
```

```{r}
df[1,3:5]
```

```{r}
df[c(1,455,1000),]
```

```{r}
df[c(511,652,121), "school"]
```

```{r}
df[c(65,515,114), 1:5 ]
```

```{r}
head(as.matrix(df))
```

```{r}
tail(as.matrix(df))
```

```{r}
head(as.matrix(df$gender))
```

```{r}
as.matrix(df)
```

```{r}
as.matrix(df$gender)
```

```{r}
as.matrix.data.frame(df)
```

```{r}
rbind(df)
```

```{r}
head(rbind(df))
```

```{r}
head(rbind(df$student_id))
```

```{r}
head(rbind(df$posttest))
```


```{r}
tail(rbind(df))
```

```{r}
cbind(df)
```

```{r}
head(cbind(df))
```

```{r}
tail(cbind(df))
```

```{r}
head.matrix(df)
```

```{r}
tail.matrix(df)
```

```{r}
cumsum(df$pretest)
```

```{r}
head(cumsum(df$pretest))
```

```{r}
tail(cumsum(df$pretest))
```

```{r}
cummax(df$pretest)
```

```{r}
head(cummax(df$pretest))
```

```{r}
tail(cummax(df$pretest))
```

```{r}
cummin(df$pretest)
```

```{r}
head(cummin(df$pretest))
```

```{r}
tail(cummin(df$pretest))
```

```{r}
cumprod(df$posttest)
```

```{r}
head(cumprod(df$posttest))
```

```{r}
head(cumprod(df$posttest), n=10)
```

```{r}
tail(cumprod(df$posttest), n=10)
```

```{r}
table(df$student_id)
```

```{r}
table(df$school)
```

```{r}
head(table(df$lunch))
```

```{r}
head(table(df$pretest))
```

```{r}
tail(table(df$pretest))
```

```{r}
head(table(df$pretest), n=10)
```

```{r}
as.table(df$posttest)
```

```{r}
head(as.table(df$posttest))
```

```{r}
tail(as.table(df$posttest))
```

```{r}
is.table(df)
```

```{r}
is.data.frame(df)
```

```{r}
is.character(df)
```
```{r}
if(class(df) == 'data.frame') TRUE else FALSE
```

```{r}
stem(df$posttest)
```

```{r}
stem(df$posttest, scale=4)
```

```{r}
with(df, stem(df$posttest[df$school == 'ANKYI']))
```

```{r}
seq_along(df)
```

```{r}
head(rnorm(df$pretest, mean = 0, sd = 1))
```

```{r}
head(rnorm(df$posttest, mean = 0, sd = 1))
```

```{r}
head(rnorm(df$n_student, mean = 0, sd = 1))
```

```{r}
head(pnorm(df$pretest, mean = 0, sd = 1))
```

```{r}
head(pnorm(df$posttest, mean = 0, sd = 1))
```

```{r}
head(qnorm(df$pretest, mean = 0, sd = 1))
```

```{r}
head(qnorm(df$posttest, mean = 0, sd = 1))
```

```{r}
head(dnorm(df$pretest, mean = 0, sd = 1))
```

```{r}
head(dnorm(df$posttest, mean = 0, sd = 1))
```

```{r}
t.test(df$pretest, df$posttest)
```

```{r}
t.test(df$pretest, df$posttest, var.equal = TRUE)
```

```{r}
t.test(df$posttest, mu = 5)
```

```{r}
t.test(df$posttest, mu = 5, alternative = 'greater')
```

```{r}
t.test(df$posttest ~ df$school, data = df, subset = df$school %in% c('ANKYI' , 'CCAAW'))
```

```{r}
wilcox.test(df$pretest, df$posttest)
```

```{r}
cor(df$pretest, df$posttest)
```

```{r}
cov(df$pretest, df$posttest)
```

```{r}
v = as.matrix(cov(df$pretest, df$posttest))
cov2cor(v)
```

```{r}
cor.test(df$pretest, df$posttest)
```

```{r}
chisq.test(df$posttest)
```

```{r}
density(df$posttest)
```

```{r}
library(dplyr)
```

```{r}
temp = df %>% filter(df$school == "ANKYI")
temp.aov = na.omit(aov(temp$pretest ~ temp$posttest, data = temp))
temp.aov
```

```{r}
summary(temp.aov)
```

```{r}
toway = aov(posttest ~ pretest * n_student, data = temp)
toway
```

```{r}
factor(df$school_setting)
```

```{r}
testCol = c(rep(df$posttest - df$pretest, length(df)))
head(testCol)
```

```{r}
testRow = c('NMIT', 'Urban', "Non-public", 263, 'Standard', 20, '1NT21SDS07', 'Female', 'NA', 00, 00)
testRow
```

```{r}
test = data.frame(df, testCol)
head(test)
```

```{r}
test = df
test['testRow',] = testRow
tail(test)
```

```{r}
test = df
test["Test",] = NA
tail(test)
```

```{r}
col(temp, as.factor = F)
```

```{r}
x = df[ , 10:11]
head(x)
```

```{r}
colMeans(x)
```

```{r}
rowMeans(x)
```

```{r}
colSums(x)
```

```{r}
rowSums(x)
```

```{r}
apply(df[ , 10:11], 2, mean)
```

```{r}
apply(df[ , 10:11], 1, mean)
```

```{r}
apply(df[ , 10:11], 2, median)
```

```{r}
apply(df[ , 10:11], 2, var)
```

```{r}
tapply(df$posttest, df$school, FUN = mean)
```

```{r}
tapply(df$posttest, df$school, FUN = var)
```

```{r}
tapply(df$posttest, df$school_setting, FUN = mean)
```

```{r}
tapply(df$posttest, df$school_type, FUN = mean)
```

```{r}
tapply(df$posttest, df$teaching_method, FUN = mean)
```

```{r}
tapply(df$posttest, df$gender, FUN = mean)
```

```{r}
tapply(df$posttest, df$lunch, FUN = mean)
```

```{r}
aggregate(df[ , 10:11], by = list(df$school), FUN = mean)
```

```{r}
aggregate(df[ , 10:11], by = list(df$school_setting), FUN = mean)
```

```{r}
aggregate(df[ , 10:11], by = list(df$school_type), FUN = mean)
```

```{r}
aggregate(df[ , 10:11], by = list(df$teaching_method), FUN = mean)
```

```{r}
aggregate(df[ , 10:11], by = list(df$gender), FUN = mean)
```

```{r}
aggregate(cbind(df$pretest, df$posttest), data = df, by = list(df$lunch), FUN = mean)
```

```{r}
aggregate(df$posttest ~ df$school, data = df, FUN = mean)
```

```{r}
aggregate(df$posttest ~ df$school * df$school_type, data = df, FUN = mean)
```

```{r}
head(na.omit(df))
```

```{r}
objects(df)
```

```{r}
ls(df)
```

```{r}
dflm = lm(posttest ~ school, data = df)
dflm
```

```{r}
cor.test(~ df$pretest + df$posttest, data = df)
```

```{r}
coef(dflm)
```

```{r}
confint(dflm)
```

```{r}
head(fitted(dflm))
```

```{r}
head(residuals(dflm))
```

```{r}
formula(dflm)
```

```{r}
dflm$call
```

```{r}
formula(df)
```

```{r}
df.m = apply(df[,10:11], 2, mean)
df.m
```

```{r}
df.sd = apply(df[ , 10:11], 2, sd)
df.sd
```

```{r}
df.s = apply(df[,10:11], 2, sum)
df.s
```

```{r}
df.1 = df.s/df.m
df.1
```

```{r}
df.se = df.sd / sqrt(df.1)
df.se
```

```{r}
df.m + df.se
```

```{r}
max(df.m + df.se)
```

```{r}
df.max = round(max(df.m + df.se) + 0.5, 0)
df.max
```

```{r}
cummeadian = function(x) {
tmp = seq_along(x)
for(i in 1:length(tmp)) tmp[i] = median(x[1:i])
print(x)}
cummeadian(temp$posttest)
```

```{r}
log2 = function(x) log(x, base = 2)
log2
```

```{r}
log2(temp$posttest)
```

```{r}
manning = function(radius, gradient, coef=0.1125) (radius^(2/3)*gradient^0.5/coef)
manning(radius = 1, gradient = 1/500)
```

```{r}
nlevels(df)
```
```{r}
df %>% filter(df$school == 'ANKYI') %>% summary()
```

```{r}
summary(filter(df, school == 'ANKYI'))
```

```{r}
tt = df %>% filter(df$gender == 'Female') %>% select(school, n_student, teaching_method, pretest, posttest)
head(tt)
```

```{r}
summary(tt)
```

```{r}
tt = df %>% filter(df$gender == 'Male') %>% select(school, n_student, teaching_method, pretest, posttest)
head(tt)
```

```{r}
summary(tt)
```

```{r}
tt = df %>% group_by(df$school) %>% summary()
tt
```

